# Site settings
title: "Data, Cloud & Container"
description: "This is the online resume / CV of Christian Richter, a solution architect with more than 15 years of experience building reliable ETL pipeline on scalable cloud infrastructure."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Christian Richter"
resume_title:                   "Solution Architect - Data, Cloud & Container"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "inquiry@crichter.me?subject=Inquiry / Anfrage"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+49 (0) 30 4193 6978"
resume_contact_address:         "Berlin, Germany"

resume_header_contact_info:     "Berlin, Germany • +49 (0) 30 4193 6978 • inquiry@crichter.me"
display_header_contact_info:    "true"

resume_header_intro: "<p>System Architect/Data Engineer with more than 15 years of experience building reliable ETL pipelines on scalable cloud infrastructre. I help organizations designing and implementing fully automated, data driven processes to support the business case using modern technology and data infrastructure. How can I help you?</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_projects:        true
resume_section_education:       true

resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/christianrichter"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/christian-richter/"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
